# Generated by Django 3.1.5 on 2021-05-10 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=4, max_digits=6)),
                ('event', models.CharField(choices=[('FX', 'Floor Exercise'), ('PH', 'Pommel Horse'), ('SR', 'Still Rings'), ('VT', 'Vault'), ('PB', 'Parallel Bars'), ('HB', 'Horizontal Bar')], max_length=2)),
                ('number_of_scores', models.PositiveIntegerField(default=0)),
                ('gymnast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Average', to='core.gymnast')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Matchup', to='core.league')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Matchup1', to='core.fantasyteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Matchup2', to='core.fantasyteam')),
            ],
            options={
                'unique_together': {('team1', 'team2', 'week')},
            },
        ),
    ]
