# Generated by Django 3.1.4 on 2021-02-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test_field',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture_url',
            field=models.TextField(blank=True),
        ),
    ]
