# Generated by Django 3.1.5 on 2021-02-07 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gymnast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roster_size', models.PositiveIntegerField()),
                ('lineup_size', models.PositiveIntegerField()),
                ('event_lineup_size', models.PositiveIntegerField()),
                ('event_count_size', models.PositiveIntegerField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='League', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meet', models.CharField(max_length=100)),
                ('floor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pommel_horse', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rings', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vault', models.DecimalField(decimal_places=2, max_digits=4)),
                ('parallel_bars', models.DecimalField(decimal_places=2, max_digits=4)),
                ('high_bar', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gymnast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Score', to='core.gymnast')),
            ],
            options={
                'unique_together': {('gymnast', 'date', 'meet')},
            },
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gymnasts', models.ManyToManyField(blank=True, related_name='FantasyTeam', to='core.Gymnast')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FantasyTeam', to='core.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FantasyTeam', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'league')},
            },
        ),
    ]
