# Generated by Django 3.1.5 on 2021-05-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='test_change',
            field=models.BooleanField(default=True),
        ),
    ]
